

import type { Metadata } from "next";
import "@fontsource-variable/geist";
import "@fontsource-variable/geist-mono";
import "./globals.css";
import FullscreenWrapper from "../components/FullscreenWrapper";
import BottomNav from "../components/BottomNav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" style={{ height: '100%', background: '#000' }}>
      <body className="bg-black text-white min-h-screen w-full overflow-hidden touch-none select-none" style={{ overscrollBehavior: 'none', WebkitUserSelect: 'none', WebkitTouchCallout: 'none', WebkitOverflowScrolling: 'touch', height: '100%', background: '#000' }}>
        <FullscreenWrapper />
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
