
"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (typeof window !== 'undefined' && window.navigator.userAgent.match(/Mobile|Android|iPhone/)) {
      document.documentElement.style.height = '100%';
      document.body.style.height = '100%';
      document.body.style.overflow = 'hidden';
      document.body.style.background = '#000';
      window.scrollTo(0, 1);
    }
  }, []);
  return (
    <html lang="fr" style={{ height: '100%', background: '#000' }}>
      <body className="bg-black text-white min-h-screen w-full overflow-hidden touch-none select-none" style={{ overscrollBehavior: 'none', WebkitUserSelect: 'none', WebkitTouchCallout: 'none', WebkitOverflowScrolling: 'touch', height: '100%', background: '#000' }}>
        {children}
      </body>
    </html>
  );
}
